
version: '3'

services:
  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/traefik.yml"
      - "./certificates:/certificates"

  streamlit-app:
    build: .
    image: streamlit-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit-app.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.streamlit-app.entrypoints=web"
    depends_on:
      - traefik
